# configtx.yaml
Organizations:
    - &OrdererOrg1
        Name: OrderingService
        ID: Orderer1MSP
        MSPDir: ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer1.fl-network.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Orderer1MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('Orderer1MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('Orderer1MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Orderer1MSP.member')"

    - &OrdererOrg2
        Name: OrderingService
        ID: Orderer2MSP
        MSPDir: ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer2.fl-network.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Orderer2MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('Orderer2MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('Orderer2MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Orderer2MSP.member')"

    - &OrdererOrg3
        Name: OrderingService
        ID: Orderer3MSP
        MSPDir: ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer3.fl-network.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Orderer3MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('Orderer3MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('Orderer3MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Orderer3MSP.member')"

    - &CompanyA
        Name: CompanyAMSP
        ID: CompanyAMSP
        MSPDir: ./crypto-config/peerOrganizations/companyA.fl-network.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CompanyAMSP.admin', 'CompanyAMSP.peer', 'CompanyAMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('CompanyAMSP.admin', 'CompanyAMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('CompanyAMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('CompanyAMSP.peer')"
        AnchorPeers:
            - Host: peer0.companyA.fl-network.com
              Port: 7051
    - &CompanyB
        Name: CompanyBMSP
        ID: CompanyBMSP
        MSPDir: ./crypto-config/peerOrganizations/companyB.fl-network.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CompanyBMSP.admin', 'CompanyBMSP.peer', 'CompanyBMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('CompanyBMSP.admin', 'CompanyBMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('CompanyBMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('CompanyBMSP.peer')"
        AnchorPeers:
            - Host: peer0.companyB.fl-network.com
              Port: 7051
Capabilities:
    # Channel capabilities apply to both the orderers and the peers and must be
    # supported by both.
    # Set the value of the capability to true to require it.
    Channel: &ChannelCapabilities
        # V2.0 for Channel is a catchall flag for behavior which has been
        # determined to be desired for all orderers and peers running at the v2.0.0
        # level, but which would be incompatible with orderers and peers from
        # prior releases.
        # Prior to enabling V2.0 channel capabilities, ensure that all
        # orderers and peers on a channel are at v2.0.0 or later.
        V2_0: true
    # Orderer capabilities apply only to the orderers, and may be safely
    # used with prior release peers.
    # Set the value of the capability to true to require it.
    Orderer: &OrdererCapabilities
        # V1.1 for Orderer is a catchall flag for behavior which has been
        # determined to be desired for all orderers running at the v1.1.x
        # level, but which would be incompatible with orderers from prior releases.
        # Prior to enabling V2.0 orderer capabilities, ensure that all
        # orderers on a channel are at v2.0.0 or later.
        V2_0: true

    # Application capabilities apply only to the peer network, and may be safely
    # used with prior release orderers.
    # Set the value of the capability to true to require it.
    Application: &ApplicationCapabilities
        # V2.0 for Application enables the new non-backwards compatible
        # features and fixes of fabric v2.0.
        # Prior to enabling V2.0 orderer capabilities, ensure that all
        # orderers on a channel are at v2.0.0 or later.
        V2_0: true

Application: &ApplicationDefaults
    Organizations:

    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies: &ApplicationDefaultPolicies
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"
      LifecycleEndorsement:
        Type: ImplicitMeta
        Rule: "MAJORITY Endorsement"
      Endorsement:
        Type: ImplicitMeta
        Rule: "MAJORITY Endorsement"

    # Capabilities describes the application level capabilities, see the
    # dedicated Capabilities section elsewhere in this file for a full
    # description
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  # Addresses used to be the list of orderer addresses that clients and peers
  # could connect to.  However, this does not allow clients to associate orderer
  # addresses and orderer organizations which can be useful for things such
  # as TLS validation.  The preferred way to specify orderer addresses is now
  # to include the OrdererEndpoints item in your org definition
  OrdererType: etcdraft
  EtcdRaft:
    Consenters:
      - Host: orderer1.fl-network.com
        Port: 7050
        ClientTLSCert: ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer1.fl-network.com/tls/server.crt
        ServerTLSCert: ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer1.fl-network.com/tls/server.crt

      - Host: orderer2.fl-network.com
        Port: 7049
        ClientTLSCert: ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer2.fl-network.com/tls/server.crt
        ServerTLSCert: ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer2.fl-network.com/tls/server.crt

      - Host: orderer3.fl-network.com
        Port: 7048
        ClientTLSCert: ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer3.fl-network.com/tls/server.crt
        ServerTLSCert: ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer3.fl-network.com/tls/server.crt
  Addresses:
    - orderer1.fl-network.com:7050
    - orderer2.fl-network.com:7049
    - orderer3.fl-network.com:7048
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  # Policies defines the set of policies at this level of the config tree
  # For Orderer policies, their canonical path is
  #   /Channel/Orderer/<PolicyName>
  Policies:
      Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
      Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
      Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
      # BlockValidation specifies what signatures must be included in the block
      # from the orderer for the peer to validate it.
      BlockValidation:
          Type: ImplicitMeta
          Rule: "ANY Writers"

  # Capabilities describes the orderer level capabilities, see the
  # dedicated Capabilities section elsewhere in this file for a full
  # description
  Capabilities:
      <<: *OrdererCapabilities

################################################################################
#
#   CHANNEL
#
#   This section defines the values to encode into a config transaction or
#   genesis block for channel related parameters.
#
################################################################################
Channel: &ChannelDefaults
    # Policies defines the set of policies at this level of the config tree
    # For Channel policies, their canonical path is
    #   /Channel/<PolicyName>
    Policies:
        # Who may invoke the 'Deliver' API
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        # Who may invoke the 'Broadcast' API
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        # By default, who may modify elements at this config level
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"


    # Capabilities describes the channel level capabilities, see the
    # dedicated Capabilities section elsewhere in this file for a full
    # description
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#
#   PROFILES
#
#   Different configuration profiles may be encoded here to be specified as
#   parameters to the configtxgen tool. The profiles which specify consortiums
#   are to be used for generating the orderer genesis block. With the correct
#   consortium members defined in the orderer genesis block, channel creation
#   requests may be generated with only the org member names and a consortium
#   name.
#
################################################################################

Profiles:
    OrdererGenesis:
      Orderer:
        <<: *OrdererDefaults
      Policies:
          Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
          Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
          Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
          LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
          Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
      Application:
          <<: *ApplicationDefaults
          Organizations:
          Capabilities:
            <<: *ApplicationCapabilities
      Consortiums:
        SampleConsortium:
          Organizations:
            - *CompanyA
            - *CompanyB
    SampleMultiNodeEtcdRaft:
        Orderer:
            <<: *OrdererDefaults
    TestTwoOrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - <<: *OrdererOrg1
        Consortiums:
            SampleConsortium:
                Organizations:
                    - <<: *CompanyA
                    - <<: *CompanyB
    CompanyChannelAB:
        <<: *ChannelDefaults
        Consortium: SampleConsortium
        Orderer:
          <<: *OrdererDefaults
          OrdererType: etcdraft
          Addresses:
            - orderer1.fl-network.com:7050
            - orderer2.fl-network.com:7049
            - orderer3.fl-network.com:7048
          Organizations:
            - *OrdererOrg1
            - *OrdererOrg2
            - *OrdererOrg3
          Capabilities:
            <<: *OrdererCapabilities
        Application:
          <<: *ApplicationDefaults
          Organizations:
              - <<: *CompanyA
              - <<: *CompanyB
        Policies:
          Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
          Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
          Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
          LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
          Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
