version: '3.7'
volumes:
  orderer1.fl-network.com:
  orderer2.fl-network.com:
  orderer3.fl-network.com:
  peer0.companyA.fl-network.com:
  peer0.companyB.fl-network.com:
networks:
  fl-network:
    driver: bridge
    external:
      name: fl-network

services:
  orderer1.fl-network.com:
    container_name: orderer1.fl-network.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=Orderer1MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer1.fl-network.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer1.fl-network.com/tls:/var/hyperledger/orderer/tls
      - ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer1.fl-network.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - fl-network
    dns:
      - 8.8.8.8   # 使用 Google DNS
      - 8.8.4.4   # 另一個備用 DNS
  
  orderer2.fl-network.com:
    container_name: orderer2.fl-network.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=Orderer2MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer2.fl-network.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer2.fl-network.com/tls:/var/hyperledger/orderer/tls
      - ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer2.fl-network.com:/var/hyperledger/production/orderer
    ports:
      - 7049:7049
    networks:
      - fl-network

  orderer3.fl-network.com:
    container_name: orderer3.fl-network.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7048
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=Orderer3MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer3.fl-network.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer3.fl-network.com/tls:/var/hyperledger/orderer/tls
      - ./crypto-config/ordererOrganizations/fl-network.com/orderers/orderer3.fl-network.com:/var/hyperledger/production/orderer
    ports:
      - 7048:7048
    networks:
      - fl-network

  peer0.companyA.fl-network.com:
    container_name: peer0.companyA.fl-network.com
    image: hyperledger/fabric-peer:latest 
    environment:
      - CORE_PEER_ID=peer0.companyA.fl-network.com
      - CORE_PEER_ADDRESS=peer0.companyA.fl-network.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.companyA.fl-network.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.companyA.fl-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.companyA.fl-network.com:7051
      - CORE_PEER_LOCALMSPID=CompanyAMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - ./crypto-config/peerOrganizations/companyA.fl-network.com/peers/peer0.companyA.fl-network.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/companyA.fl-network.com/peers/peer0.companyA.fl-network.com/tls:/etc/hyperledger/fabric/tls
      - ./crypto-config/peerOrganizations/companyA.fl-network.com/peers/peer0.companyA.fl-network.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    networks:
      - fl-network

  peer0.companyB.fl-network.com:
    container_name: peer0.companyB.fl-network.com
    image: hyperledger/fabric-peer:latest 
    environment:
      - CORE_PEER_ID=peer0.companyB.fl-network.com
      - CORE_PEER_ADDRESS=peer0.companyB.fl-network.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.companyB.fl-network.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.companyB.fl-network.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.companyB.fl-network.com:8051
      - CORE_PEER_LOCALMSPID=CompanyBMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - ./crypto-config/peerOrganizations/companyB.fl-network.com/peers/peer0.companyB.fl-network.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/companyB.fl-network.com/peers/peer0.companyB.fl-network.com/tls:/etc/hyperledger/fabric/tls
      - ./crypto-config/peerOrganizations/companyA.fl-network.com/peers/peer0.companyB.fl-network.com:/var/hyperledger/production
    ports:
      - 8051:8051
      - 8052:8052
      - 8053:8053
    networks:
      - fl-network

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      # - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.companyA.fl-network.com:7051
      - CORE_PEER_LOCALMSPID=CompanyAMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/companyA.fl-network.com/peers/peer0.companyA.fl-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/companyA.fl-network.com/peers/peer0.companyA.fl-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/companyA.fl-network.com/peers/peer0.companyA.fl-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/companyA.fl-network.com/users/Admin@companyA.fl-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer1.fl-network.com
      - orderer2.fl-network.com
      - orderer3.fl-network.com
      - peer0.companyA.fl-network.com
      - peer0.companyB.fl-network.com
    networks:
      - fl-network
